### ISSUE TITLE
Nerd Font アイコンをバンドルしてほしい

### ISSUE THREAD

**Issue by mochi-sann** [yuru7/udev-gothic#1]
ライセンスの関係上難しいかもしれませんが
https://www.nerdfonts.com のアイコンフォントもバンドルしてほしいです

**Comment by mochi-sann** [comment]
https://github.com/ryanoasis/nerd-fonts/blob/master/readme_ja.md#%E3%81%9D%E3%81%AE-8-%E8%87%AA%E5%88%86%E3%81%A7%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E3%81%AB%E3%83%91%E3%83%83%E3%83%81%E3%82%92%E5%BD%93%E3%81%A6%E3%82%8B
にもある通り 下記のDockerコマンドを実行するか
```bash 
docker run -v /path/to/fonts:/in -v /path/for/output:/out nerdfonts/patcher
```
Nerd font リポジトリに含まれる 

https://github.com/ryanoasis/nerd-fonts/blob/master/font-patcher 

を実行すればNerdFontのアイコンを追加できるようです。

**Comment by yuru7** [comment]
情報ありがとうございます。

日本語フォントでは、等幅フォントにするための設定値などが英字フォントと比べて少々クセがあり、その影響か、単純にNerd Fonts提供のパッチを当てると文字幅がおかしくなった記憶があります。（まだフォントの設定値の理解が曖昧なHackGenのときに試したことなので、もしかしたら違うかもしれません）

そのため、もし対応するなら公式パッチを当てるのではなく、公式で提供されているパッチ済みフォントからアイコン部分のみを抽出し、幅を調整しつつ、UDEV Gothicに合体させていく方法を取ることになります。

対応有無も含め、引き続き検討します。

**Comment by mochi-sann** [comment]
ありがとうございます。パッチを当てるだけの単純なものではないんですね

**Comment by yuru7** [comment]
[v0.0.6](https://github.com/yuru7/udev-gothic/releases/tag/v0.0.6) にて対応したため、本issueはクローズします。
