### ISSUE TITLE
Windows 10で罫線文字が全角にならない

### ISSUE THREAD

**Issue by udaken** [yuru7/udev-gothic#10]
- Windows 10 21H2
- UDEV Gothic JPDOC version 0.1.0

Windows の メモ帳 および サクラエディタ で罫線を UDEV Gothic JPDOC で表示させると、半角扱い？の様になり崩れてしまいます。
```
使用するテキスト:
┌─┬┐
│　││
├─┼┤
└─┴┘
```

![image](https://user-images.githubusercontent.com/7896698/163505204-84b17533-c7eb-43cf-92c2-3ecc1314cff4.png)

BIZ UDゴシック、HackGen では崩れずに表示されます。

---

メーラーで使用すると、とても見やすくなり気に入ってます。🙏

**Comment by yuru7** [comment]
ご報告ありがとうございます。

これは不具合ではなく、現行の仕様となります。
JPDOC版は一部の記号をJetBrains Mono(半角)よりBIZ UDゴシック(全角)が優先されるように適用していますが、v0.1.0時点では、罫線記号類はその対象となっていません。

しかし実は、次のバージョンでは罫線記号類でもBIZ UDゴシックが優先されるようにするつもりです。
もし、いち早く試してみたい場合は、以下にビルド済みのフォントをアップロードしていますので、個別にダウンロードしてお試しください。

https://github.com/yuru7/udev-gothic/tree/issue10/build_dev

**Comment by udaken** [comment]
回答ありがとうございます。
「日本語文書で頻出する記号類」に罫線文字も含まれると思っていたのですが、違うのですね。

アップロードしていただいたフォントなら期待通りに表示できました。
次バージョンの公開楽しみに待っています！
