### ISSUE TITLE
Nerd Font非対応の文字がある

### ISSUE THREAD

**Issue by 0keke** [yuru7/udev-gothic#12]
READMEにあるような旧字体以外でも、Nerd Font非対応の文字があるように見受けられます（例えば、Hex:ea8aなど）。
こちらとは別リポジトリなりますが、HackGenNerd、PlemolJPなどでも同様です。

<img width="219" alt="スクリーンショット 2023-01-14 23 06 46" src="https://user-images.githubusercontent.com/61049444/212475987-df00150d-067f-4861-9fe8-2dd9c6980ae7.png">

※もとの[Ned Font](https://www.nerdfonts.com)から、例えばHack Nerd Fontを試してみると、アイコンが表示されます。

**Comment by yuru7** [comment]
ご報告ありがとうございます。
画像からだと対象のコードポイントが分からないため、認識されている表示不良文字のコードポイント一覧をいただくか、コードブロック記法の中にそのまま貼り付けていただくことはできますか？

**Comment by 0keke** [comment]
現時点で確認しているのは、次の通りです。
この書き方で確認できますか？

-  :<> 60042, Hex ea8a, Octal 165212,
-  :<> 60047, Hex ea8f, Octal 165217,
-  :<> 60251, Hex eb5b, Octal 165533,
-  :<> 60252, Hex eb5c, Octal 165534,
-  :<> 60253, Hex eb5d, Octal 165535,
-  :<> 60044, Hex ea8c, Octal 165214,
-  :<> 60053, Hex ea95, Octal 165225,
-  :<> 60254, Hex eb5e, Octal 165536,
-  :<> 60038, Hex ea86, Octal 165206,
-  :<> 60255, Hex eb5f, Octal 165537,
-  :<> 60027, Hex ea7b, Octal 165173,
-  :<> 60044, Hex ea8c, Octal 165214,
-  :<> 60257, Hex eb61, Octal 165541,
-  :<> 60051, Hex ea93, Octal 165223,
-  :<> 60258, Hex eb62, Octal 165542,
-  :<> 60044, Hex ea8c, Octal 165214,
-  :<> 60201, Hex eb29, Octal 165451,
-  :<> 60043, Hex ea8b, Octal 165213,
-  :<> 60048, Hex ea90, Octal 165220,
-  :<> 60043, Hex ea8b, Octal 165213,
-  :<> 60260, Hex eb64, Octal 165544,
-  :<> 60201, Hex eb29, Octal 165451,
-  :<> 60261, Hex eb65, Octal 165545,
-  :<> 60214, Hex eb36, Octal 165466,
-  :<> 60262, Hex eb66, Octal 165546,
-  :<> 60301, Hex eb8d, Octal 165615,
-  :<> 60049, Hex ea91, Octal 165221,
-  :<> 60051, Hex ea93, Octal 165223,
-  :<> 60050, Hex ea92, Octal 165222,
-  :<> 60054, Hex ea96, Octal 165226,
-  :<> 60051, Hex ea93, Octal 165223,
-  :<> 60040, Hex ea88, Octal 165210,
-  :<> 60115, Hex ead3, Octal 165323,

**Comment by yuru7** [comment]
大変遅レスですみません。
手元の環境で確認してみたところ、特に問題なく表示されるようです。フォントバージョンやフォントファミリーがNerd Fonts合成版なのかなど、確認してみてください。

確認環境:

- Windows 11 64bit 22H2
- UDEV Gothic NFLG: v1.2.0

![image](https://user-images.githubusercontent.com/13458509/231716341-03d9ab69-d95c-4ec3-9c43-11bccd3dac98.png)

**Comment by 0keke** [comment]
お返事大変遅くなりました。
確かに、windowsのGvim、windows-teminalなどでは問題なく表示できています。
MacのiTterm2でのみ表示できないようです。
問題は解決していないので、mac環境では別フォントを使うことにし、また詳細がわかる際に報告させていただきます。
こちらはcloseしていただいてもOKです。

**Comment by matsuu** [comment]
iTerm2で試してみましたが問題なく表示されているように見えました。iTerm2の設定はほぼデフォルトでフォント設定を変えただけだと思います。

* macOS Ventura 13.5
* iTerm2 バージョン3.4.16
* UDEV Gothic NF バージョン1.3.1（homebrewでインストール）

フォント設定周りも含めたスクリーンショット

![iterm2 + UDEV Gothic NF](https://github.com/yuru7/udev-gothic/assets/4395/9b125bc0-14d2-4383-aae5-0d42c4456c69)

**Comment by matsuu** [comment]
`Use a diffferent font for non-ASCII text` のチェックボックスを有効にしてそちらでUDEV Gothic NFを選択した場合はNerdFontは表示されませんでした。

**Comment by 0keke** [comment]
確認していただきありがとうございます。原因がわかっていないため、不可解なのですが、手元マシンでもフォント再インストールで症状が改善しましたので、こちらはcloseとさせてください。
長らく期間が空いてしまったため、当初の原因は不明ですが、丁寧にお付き合いいただきありがとうございました。
