### ISSUE TITLE
丸数字（①②など）がiTerm上で半角幅と認識されてしまう

### ISSUE THREAD

**Issue by harajune** [yuru7/udev-gothic#13]
丸数字をiTermで入れると文字が重なってしまうようです。
iTermやzshの設定の問題な可能性もあるかもしれません。
VSCodeでは問題なく読めました。

### 環境
- macOS 13.2（22D49）
- iTerm Build 3.4.19
- zsh 5.8_1
- 使用フォント UDEV Gothic JPDOC v1.1.0

### 起きていること
丸数字を入れると、丸数字自体は全角だが、スペースが半角分しか取られないため後ろの文字とかぶってしまう。
![image](https://user-images.githubusercontent.com/56193/221405146-72ec36ba-d9cb-41fd-8596-ce679280ba1b.png)

**Comment by yuru7** [comment]
残念ながら私の手元の環境にmacが無いため、再現調査ができません…。

推測で話をすると、丸数字記号はEast Asian Ambiguous Widthに該当する文字ですので、以下の問題が発生しているのではないかと思います。
[East Asian Ambiguous Width問題](https://github.com/hamano/locale-eaw)

これはフォント側では全角幅で定義されていても、特定アプリケーションではその幅が無視され異なる幅で表示されることが原因で起こる事象です。
よって、この問題であればフォントの不具合ではありません。

なお、この問題に対処する方法は以下のいずれかだと思われます。

- アプリケーションのEast Asian Ambiguous Width関連設定を見直す
- East Asian Ambiguous Widthの記号が半角となるフォントを使う（JPDOC版で無いものが概ねこれに該当します）
- フォント側の設定幅を正しく認識するアプリケーションを使用する

私のところにmac環境が無いのでググっただけで試せていませんが、以下の記事も参考になるかもしれません。
https://qiita.com/seto-r/items/706d2c4d795dba7d42ed
