### ISSUE TITLE
VSCodeのターミナルでUDEV Gothic NFを正しく表示させたい。

### ISSUE THREAD

**Issue by mendelssohnbach** [yuru7/udev-gothic#15]
使用OS

```
cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

VSCodeバージョン

```
code --version
1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
```

gnome-terminalにて[フォントを指定]にチェックし、
[UDEV Gothic NF]を指定 。
結果
![gnome-terminal](https://user-images.githubusercontent.com/20514055/235569134-6676d4bf-a1aa-4f34-9ee2-1e2323458b67.png)

VSCodeのワークスペース設定とし[.vscode/settings.json]にて以下を記述

```
  },
  "terminal.integrated.fontFamily": "UDEV Gothic NF"
}
```

結果
![VSCode-terminal](https://user-images.githubusercontent.com/20514055/235569300-a51b6450-7fc7-4802-9cb7-6f2c17de9d8a.png)

アイコンが期待した通りに表示されません。

私の[.vscode/settings.json]は、どこが間違っていますか？

**Comment by yuru7** [comment]
Win 11 x64 + VSCode 1.77.3 で以下の設定で確認しましたが、私の環境では正しく表示されます。

```
"terminal.integrated.fontFamily": "UDEV Gothic NF"
```

![image](https://user-images.githubusercontent.com/13458509/235590207-f2ccf757-9d36-4b11-a6ef-e2d69270bc5c.png)

Gitのアイコンやnodeのアイコンが表示されるのを確認できていますので、フォントの問題ではないと思います。

> 私の[.vscode/settings.json]は、どこが間違っていますか？

すみませんが各エディタでの設定を私の方でサポートはしませんので、VSCodeの不具合ならそちらのリポジトリのissueに書くか、設定内容であれば他のエンジニアに質問できるようなフォーラムで聞いていただくのがよいと思います。

**Comment by mendelssohnbach** [comment]
UDEV Gothicの問題ではないと確認いただきありがとうございました。
