### ISSUE TITLE
半角1:全角2のフォントでU+01D1 LATIN CAPITAL LETTER O WITH CARONのグリフ幅が全角(2048)になっている

### ISSUE THREAD

**Issue by ekfacile** [yuru7/udev-gothic#16]
v1.3.0で確認。

他の欧文グリフのグリフ幅は半角(1024)になっているので、縮小漏れだと思われます。

**Comment by yuru7** [comment]
現状、仕様通りです。

本フォントにおいて、基本的に「全角幅を半角幅に縮小」の加工は行っていません。半角幅になっているグリフのほとんどは、JetBrains Mono由来のものが合成時に優先されているのが理由です。例えば `U+01D1` の近辺である `U+01
D0` や `U+01D2` が半角になっているのは、JetBrains Monoに含まれているからです。

こういった仕様であることを踏まえると、BIZ UDゴシックとJetBrains Monoのいずれかにしか含まれていないグリフは、必ず存在する方が優先されます。
`U+01D1` は、BIZ UDゴシック側にのみ含まれるため、全角となっています。

左がBIZ UDゴシック、右がJetBrains Mono
![image](https://github.com/yuru7/udev-gothic/assets/13458509/f6fef54c-66c4-4ff1-963f-0f7526d50243)
