### ISSUE TITLE
Consider adding a Latin-only version?

### ISSUE THREAD

**Issue by rami3l** [yuru7/udev-gothic#17]
Thank you for making this custom version of JetBrains Mono!
In fact, I've been using it for quite a while and I really love it!

I'm fully aware that this is intended to be a programming font mainly for Japanese developers, but as a Chinese user, I also find the 1:2 and 3:5 widths very helpful for my use case, it is just that the Chinese character set is not fully covered by the embedded Japanese font, and combined with certain font fallback configurations it might look inconsistent:

<img width="495" alt="image" src="https://github.com/yuru7/udev-gothic/assets/33851577/d66f4abb-9899-4c2d-abeb-c393de342b22">

It would be so nice if a Latin-only version could be added to the build pipeline, just like another widely-used Japanese programming font [M+](https://github.com/coz-m/MPLUS_FONTS) already has!  [^1] This should not only allow me to customize the Chinese fallback stack myself, but also help other people who want to embed this font in certain use cases.

Thanks again for all the nice work! 🙏

[^1]: The `M PLUS Code Latin 50/60` variants stand for Latin-only versions of 50% and 60% fullwidth.

**Comment by yuru7** [comment]
Thanks for using this font.

Sorry, but I am not too keen on making a Latin-only version. Because the advantage of using this font is that "the Latin and Japanese fonts are combined in just the right size". If I made just the Latin font, it would be almost the same as JetBrains Mono.

**Comment by rami3l** [comment]
@yuru7 Thanks all the same :)
