### ISSUE TITLE
カタカナとの混同を避ける

### ISSUE THREAD

**Issue by JapanYoshi** [yuru7/udev-gothic#19]
カタカナの `エ` `ニ` `ロ` `ー` と混同される可能性が高い文字を、漢字は明朝体のウロコを付けて、長音符は曲げて区別すべきと思います。

![IMG_20240214_122502](https://github.com/yuru7/udev-gothic/assets/8707990/d5c8d23f-0519-4a69-aa2d-eb2af932da64)

Firgeで使用されているアプローチの延長です。

![](https://user-images.githubusercontent.com/13458509/121860146-87c82880-cd33-11eb-8c8a-3838ec926d69.png)

**Comment by yuru7** [comment]
ご意見ありがとうございます。
BIZ UDゴシックの美しさを損なってしまうため、本フォントにおいては日本語グリフにクセ付けはしないことを基本方針として制作していたため、申し訳ないですが却下させていただきます🙇‍♂️
