### ISSUE TITLE
等幅フォントでも日本語文書で頻出する記号類を優先してほしい

### ISSUE THREAD

**Issue by ShigeUe** [yuru7/udev-gothic#2]
便利に使わせていただいています。
等幅フォントでも日本語文書で頻出する記号類 ( ← ↓ ↑ → □ ■ … など) をBIZ UDゴシックの全角記号が優先されるようにしてほしいです。

**Comment by yuru7** [comment]
すみません、要望の内容が理解できていないので、まず確認させてもらえますか？

「等幅フォントでも」と仰っていますが、そもそもUDEV Gothicが提供するバリエーションは全て、等幅フォントです。また、日本語文書で頻出する記号類をBIZ UDゴシックの全角記号を優先するようにしているのは、v0.0.5から同梱しているJPDOC版となります。

したがって、ご要望のものはJPDOC版のものが満たしているのではないか、と考えていますが、これだと何か不足があるのでしょうか？

**Comment by ShigeUe** [comment]
大変申し訳ありません。こちらの確認ミスです。
穴があったら入りたい・・・
