### ISSUE TITLE
Nerd Fonts対応版のIVS対応が2.0.0のリリースノートに書かれていない

### ISSUE THREAD

**Issue by tats-u** [yuru7/udev-gothic#22]
Nerd Fonts 3.0で、CJK互換漢字に被さっていたグリフが丸々Unicodeの私用面（U+F0000以降）に移動したため、IVSを無効化する理由がなくなりました。

https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#overview

そのため、Nerd Fonts対応版では現在無効化しているIVSに再び対応するようにしてくださると嬉しいです。

https://codepen.io/tats-u/pen/GRbxvbJ

![image](https://github.com/user-attachments/assets/83307b12-b78e-443c-83f2-763fcbc0d033)

----

P.S. 2.0.0インストール後

![image](https://github.com/user-attachments/assets/9ebef66f-1973-4ae7-a628-b28f7a0b4c6f)

**Comment by yuru7** [comment]
v2.0.0 ではNerd Fonts版でIVSを除外していないので、ご希望の表示になっているかもしれません。よろしければ試してみてください。

手元のテキストエディタで確認した結果 (UDEV Gothic NF):
![image](https://github.com/user-attachments/assets/6d301089-9b45-4ede-9ac6-ce6f203793a0)

**Comment by tats-u** [comment]
おっしゃる通りでした。

![image](https://github.com/user-attachments/assets/9ebef66f-1973-4ae7-a628-b28f7a0b4c6f)

2.0.0のリリースノートに追記してくださいませんでしょうか。

**Comment by tats-u** [comment]
確認しました。ご対応感謝します。
