### ISSUE TITLE
OFLの準拠

### ISSUE THREAD

**Issue by tani** [yuru7/udev-gothic#3]
素晴しいフォントの数々をありがとうございます．
さて，yuru7さんのフォントの多くはOFLで公開されているフォントをリミックスして新しいフォントを作成していますね．

OFLの第二条項には，

> Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license.
> (抄訳) フォントのオリジナルもしくは改変版は，任意のソフトウェアと，バンドルされたり，再配布されたり，販売されたりします．ただし (provided that)，この複製物は上記の著作権表示とこのライセンスを含めてください．

とあります．そして，さらにOSSの一般の慣例に照し合せても改変したものを公開する場合，オリジナルのフォントの著作権表示を作品に含める義務があります．

しかし，yuru7さんのフォント (Udev Gothic/HackGen/Firage/Plemol)について調べたところ，
著作権表示の義務を果していなさそうです．OFL違反であるのはYuru7さんの意図しているところではないと思いますでの
修正をしてはいかがでしょうか?

正しい例としてNerd Fontsは，この条項を遵守していますので．参考にしてみてください．
https://github.com/ryanoasis/nerd-fonts/search?q=Copyright

**Comment by yuru7** [comment]
ご指摘ありがとうございます。浅学ゆえ、大変助かります。

さて、以下の通りLICENSE上でソースフォントのライセンスについて言及することにしつつ、各ソースフォントのライセンスもリポジトリ上に格納するようにしました。
これで、taniさんの観点から、ご指摘の点は充足できているように思えますでしょうか？

https://github.com/yuru7/udev-gothic/blob/main/LICENSE

**Comment by yuru7** [comment]
> 2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.

"stand-alone text files" とあるので、ライセンステキストを用意した今の状態で最低条件は満たしていそうですが、もっと踏み込んで、フォント内の著作権フィールドに各ソースフォントの著作権表示を含めるのがより丁寧ではありそうです。（ちょうどCicaフォントが対応しているのを見かけました）

**Comment by tani** [comment]
対応ありがとうございます．
yuru7さんの認識で問題ありません．たしかにCopyrightフィールドに追記するのがより親切だと思います．
pythonのFontToolsを使用しているのであれば，以下のように追記することができますので，
参考にしてくださいませ．

https://github.com/tani/artistic-code-pro/blob/f8f41e144abf1bb8c8c8486247b6a57724d16c71/script/metadata.py#L20-L28

**Comment by yuru7** [comment]
v0.0.8 よりソースフォント群のCopyrightもフォント本体に埋め込むようにしたため、クローズします。

ご指摘ありがとうございました。
