### ISSUE TITLE
LG系のフォントにおけるバッククオートの高さについて

### ISSUE THREAD

**Issue by masaha03** [yuru7/udev-gothic#4]
LG系のフォントのみ、オリジナルのJetBrains Monoと異なり、バッククオートが行の目一杯上の位置になっています。以下はVisual Studio Codeで確認した画像です。

 - UDEV Gothic 35LG
![image](https://user-images.githubusercontent.com/694411/160514397-c84ccebf-7fef-49e9-b7cc-1b14255de726.png)

 - JetBrains Mono
![image](https://user-images.githubusercontent.com/694411/160514453-df6669ef-1e77-4ccc-8f13-539404559efa.png)

フォントについては素人なので、バグなのか仕様なのか判別できないのですが、JetBrains Monoと同じ高さの方が見やすく感じます。

ともあれ、素晴らしいフォントの開発ありがとうございます！
JetBrains Monoを愛用していたのですが、日本語はあきらめてたのでうれしいです。

**Comment by yuru7** [comment]
ご報告ありがとうございます。

仕様かどうか、で言うとこれは仕様です（JetBrains Monoの）。
JetBrains Monoのリガチャありのものを見ていただくと分かりますが、 ` `` ` と ` `a` ` で、バッククォートの垂直位置が変わるのが見て取れるかと思います。

しかしながら、「別に連続したバッククォートの位置、変える必要無くない？」と個人的には思うので、垂直位置が変わらないようにできないか検討します。

**Comment by yuru7** [comment]
垂直位置の調整を試みましたが、今のビルドスクリプト内で機械的にやるには、やり方をよく検討する必要がありそうで、ちょっと時間を要しそうです。

また、行内でかなり高い位置にあるのは確かですが、見えないほどではないことや、エディタ側の設定で行の高さは広げることができる（VSCodeであれば `"editor.lineHeight"` の設定で可能 ）ことを鑑みまして、すみませんが「バッククォートの高さ調整は現時点では行わない」という結論とさせてください。

**Comment by masaha03** [comment]
確認ありがとうございます！
手元のJetBrains Monoでは画像の通りバッククオートの位置が変わらなかったので、理解に苦しんだのですが、インストールしていたJetBrains Monoのバージョンが古かったようです。
最新版ではUDEV GothicのLG系と同じ仕様であることを確認できました。

連続したバッククオートのリガチャは多分マークダウンのコードブロックのためのものだと思いますが、コードブロックが連続しているときに、間に空行があるのかないのか、あるのであればどこにあるのかが非常に分かりにくく感じました…。もしバグなのであれば、と思ったのですが、JetBrains Monoの仕様通りということであれば、自分を慣れさせる方向でいきたいと思います。
迅速な対応ありがとうございました！
