### ISSUE TITLE
===がリガチャしないケースがあります

### ISSUE THREAD

**Issue by kazaoki** [yuru7/udev-gothic#6]
とても素敵なフォントセット、ありがとうございます。
気になった点がありましたのでイシューします。

以下のようなプログラムのIF文で、先に書いたリテラルをマルチバイトにするとイコール３つのリガチャが解除されてしまいます。
```js
if('あああ'===data) { ; }
```

以下、実際のキャプチャ画面です。
確認したのは Windows10 + VSCode 1.65.2 ＋ フォント設定 `UDEV Gothic LG` です。

![not-lg](https://user-images.githubusercontent.com/6366870/160727090-06406f8d-ad51-48ca-9e9c-40f88490cd61.png)

修正ご検討いただけましたら幸いです。
m(_ _)m

**Comment by yuru7** [comment]
ご報告ありがとうございます！
これは、かなり奇妙な現象ですね…。

原因を追求することは困難だったのですが、ひとまず対症療法的な対処は見つかりましたので、次のバージョンで対応します。

**Comment by yuru7** [comment]
[v0.0.9](https://github.com/yuru7/udev-gothic/releases/tag/v0.0.9) にて対応しました。ご報告ありがとうございました🙇‍♂️

**Comment by kazaoki** [comment]
正常にリガチャされるようになったことを確認できました！
ご対応誠にありがとうございました！
![fixed-lg](https://user-images.githubusercontent.com/6366870/160835045-e837727d-be92-4c46-b35a-3f3cedeb2b87.png)
