### ISSUE TITLE
斜体の日本語が一部小さく表示される

### ISSUE THREAD

**Issue by yutkat** [yuru7/udev-gothic#8]
ターミナル上のエディタで斜体表示を有効にしていると、斜体の日本語の一部が小さく表示されてしまいます。

![2022-04-03_18-56](https://user-images.githubusercontent.com/8683947/161422040-07e22a33-fcd6-4db0-8cec-4b08ab9e909e.png)

Cicaだとうまく表示されます
![2022-04-03_18-56_1](https://user-images.githubusercontent.com/8683947/161422055-9688c4c3-4432-4895-996b-a40d87792170.png)

- UDEV Gothicバージョン: v0.0.9
- UDEV Gothicバリエーション: UDEV Gothic 35NFLG
- OS: ArchLinux
- Terminal: wezterm

**Comment by yuru7** [comment]
ご報告ありがとうございます。

取り急ぎUbuntu上のWezTermで確認してみましたが、斜体表示において同じような状況が見て取れました。
ただ原因は、フォント側というよりWezTerm側にあるようです。

Italicスタイルが存在しない日本語フォントでこの事象が起こるようです。逆に言うと、日本語フォントでもItalicスタイルがインストールできていれば、正常に表示できます。

以下は、いくつかのフォントで試した結果です。Cicaは、Italicスタイルも提供されているので、未インストール状態と、インストール状態で比較しています。未インストール状態だと、同事象が起こることが見て取れます。
また、UDEV Gothic 35NFLGでもフォントサイズを変えると再現しない場合があるようです。
Noto Sans CJK JPの結果は、公開元が信頼できる団体かつ、Italicスタイルが提供されていない日本語フォントということで比較対象に加えていますが、やはり再現するようです。

Cica (Italic 未インストール / font_size = 12)
![image](https://user-images.githubusercontent.com/13458509/161452336-101e6b74-e445-4f93-bbb6-9c909d4a66c0.png)

Cica (Italic インストール済み / font_size = 12)
![image](https://user-images.githubusercontent.com/13458509/161452658-2715c38c-0dcc-4629-af66-0496c2b19c7e.png)

UDEV Gothic 35NFLG (font_size = 12)
![image](https://user-images.githubusercontent.com/13458509/161452360-889dab44-e595-4e1a-803a-063a926a25a9.png)

UDEV Gothic 35NFLG (font_size = 11)
![image](https://user-images.githubusercontent.com/13458509/161452372-5cd3edc6-6611-4042-b160-d0d01665d540.png)

Noto Sans CJK JP (font_size = 12)
![image](https://user-images.githubusercontent.com/13458509/161452529-9ae3295a-82f6-4560-8d21-42790434f9b4.png)

**Comment by yutkat** [comment]
なるほど。ありがとうございます。
たしかにフォントサイズ12だとうまく表示されました。

フォント側の問題でないとのことなのでクローズしたいと思います。
調査ありがとうございました :bow:

**Comment by yutkat** [comment]
weztermの設定に
```lua
	font_rules = {
		{
			italic = true,
			font = wezterm.font("Cica", { italic = true }),
		},
	},
```
を追加することで対応できました。お騒がせしました。

**Comment by yuru7** [comment]
@yutkat 
v0.0.10 でイタリック体を追加してみました。インストールすれば、正しく表示されるようになるかもしれません。

**Comment by yutkat** [comment]
おしゃれな斜体になりましたー :bow: 
ありがとうございます :joy: 
![2022-04-04_22-51](https://user-images.githubusercontent.com/8683947/161558728-c6d9768c-5e04-4b95-8e69-6d0ea93d1b44.png)

**Comment by yuheitomi** [comment]
Italic 対応ありがとうございました！
